-- users
create table if not exists `users`(
	id int auto_increment comment '主键标识',
	username varchar(255) comment '用户名称',
	password varchar(255) comment '密码',
	enabled tinyint(1) comment '账户是否可用',
	PRIMARY KEY(id)
);

-- authorities
create table if not exists `authorities`(
	id int auto_increment comment '主键标识',
	username varchar(255) comment '用户名称',
	authority varchar(255) comment '授权码',
	PRIMARY KEY(id)
);

-- orders
create table if not exists `orders`(
	id int auto_increment comment '主键标识',
	`order_num` varchar(255) comment '订单编号',
	`operator` varchar(255) comment '操作员',
	PRIMARY KEY(id)
);

create sequence `hibernate_sequence` start with 1 increment by 1;

create table orders_aud (
	id bigint not null, 
	rev integer not null, 
	revtype tinyint, 
	operator varchar(255), 
	order_num varchar(255), 
	primary key (id, rev)
);
	
create table revinfo (
	rev integer generated by default as identity, 
	revtstmp bigint, 
	primary key (rev)
);

alter table orders_aud add constraint FKinujab7ljkelflu16c9jjch19 foreign key (rev) references revinfo;